jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "thibaut"
        name: "thibaut humbert"
        password: ${JENKINS_PASSWORD}
      - id: "chocolateen"
        name: "Hugo"
        password: ${USER_CHOCOLATEEN_PASSWORD}
      - id: "vaugie_g"
        name: "Garance"
        password: ${USER_VAUGIE_G_PASSWORD}
      - id: "i_dont_know"
        name: "Jeremy"
        password: ${USER_I_DONT_KNOW_PASSWORD}
      - id: "nasso"
        name: "Nassim"
        password: ${USER_NASSO_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permission:
              - "Overall/Read"
              - "Overall/Administer"
            assignements:
              - "chocolateen"
          - name: "ape"
            description: "Pedagogical team member"
            permission:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Read"
            assignements:
              - "i_dont_know"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permission:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Create"
              - "Job/Read"
              - "Job/Configure"
              - "Job/Delete"
              - "Job/Move"
              - "Job/Workspace"
              - "Job/Cancel"
            assignements:
              - "vaugie_g"
          - name: "assist"
            permission:
              - "Job/Read"
              - "Overall/Read"
              - "Job/Workspace"
            description: "Assistant"
            assignements:
              - "nasso"

jobs:
  - file: /job_dsl.groovy